# Generated by Django 4.2.4 on 2023-08-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('artista_nombre_artistico', models.CharField(max_length=50)),
                ('artista_verificado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=300)),
                ('fecha_composicion', models.DateField()),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.artista')),
            ],
        ),
    ]
